
sudo: required
dist: trusty

language: node_js

node_js:
  - "4"
  - "6"

branches:
  only:
  - master

before_script:
  - npm install -g egg-bin
  - npm install -g coveralls

after_script:
  - nvm use 6
  - npm run coverage
